name:                fakedata-quickcheck
version:             0.8.0
license:             MIT
author:              "Jappie Klooster"
maintainer:          "jappieklooster@hotmail.com"
copyright:           "2020 Jappie Klooster"

extra-source-files:
- Readme.md
- LICENSE

ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -Wincomplete-record-updates
    - -Widentities

# from https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/
default-extensions:
  # trivial
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - InstanceSigs
  - MultiParamTypeClasses
  # only activated once used
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - TupleSections
  # no cost deriving power
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - StandaloneDeriving
  # used everywhere anyway
  - OverloadedStrings
  # ehh syntax
  - TypeApplications

dependencies:
- base >= 4.7 && < 5
- QuickCheck >= 2.6 && < 2.15
- fakedata >= 0.6.0 && < 0.9.0
- random  >= 1 && < 1.2.0

library:
  source-dirs: src

tests:
  unit:
    main:                Spec.hs
    source-dirs:
    - test
    dependencies:
    - hspec
    - hspec-core
    - fakedata-quickcheck
    - regex-tdfa
    - text
