name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: cachix/install-nix-action@v13
    - uses: cachix/cachix-action@v10
      with:
        name: jappie
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # Only needed for private caches
        #authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-shell --run "echo OK"
    - name: tests
      shell: bash
      run: |
        set -ex
        nix --version
        make shell-lts18
