name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        resolver: [lts18, lts16, lts14]
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: cachix/install-nix-action@v13
    - uses: cachix/cachix-action@v10
      with:
        name: jappie
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: tests
      shell: bash
      run: |
        set -ex
        export NIX_PATH="nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/tags/21.05.tar.gz"
        nix --version
        make shell-${{ matrix.resolver }}
        stack --nix test
